name: CI Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (sanity)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          python -c "print('CI sanity check ✅')"
      - name: Build Docker image
        run: docker build -t devops-demo .
